// Info: Builds the defects list from machine output only: the Playwright
// JSON report (`_test/test-results/browser.json`) and the Node test TAP
// output (`_test/test-results/node.tap`). Every row is a failed check with
// its component, expected and actual values, location and any screenshot
// path. Nobody types a row; a defect that a check did not catch is a gate
// defect first.
//
// Usage: node scripts/defects.js [--out <path>]   (default: ../__dev__/DEFECTS.md)

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { REPO_ROOT } from './lib/components.js';

const outIndex = process.argv.indexOf('--out');
const OUT = outIndex === -1 ? resolve(REPO_ROOT, '..', '__dev__', 'DEFECTS.md') : resolve(process.argv[outIndex + 1]);
const RESULTS = join(REPO_ROOT, '_test', 'test-results');

const rows = [];


/********************************************************************
Component name from a test title (`Icon / default`, `Icon: ...`).

@param {String} title - Test title

@return {String}
*********************************************************************/
function componentOf (title) {

  const match = title.match(/^([A-Z][A-Za-z0-9]*)\s*[/:]/);

  return match ? match[1] : '-';

}


/********************************************************************
Expected and actual from an assertion message, when it carries them.

@param {String} message - Error text

@return {Object} - { expected, actual }
*********************************************************************/
function expectation (message) {

  const expected = (message.match(/Expected:?\s*(.+)/i) || [])[1] || '';
  const actual = (message.match(/(?:Received|actual):?\s*(.+)/i) || [])[1] || '';

  return { expected: expected.trim().slice(0, 120), actual: actual.trim().slice(0, 120) };

}


// Playwright JSON report
const browser = join(RESULTS, 'browser.json');
if (existsSync(browser)) {
  const report = JSON.parse(readFileSync(browser, 'utf8'));
  const walk = function (suite, path) {
    for (const spec of suite.specs || []) {
      for (const test of spec.tests || []) {
        for (const result of test.results || []) {
          if (result.status === 'passed' || result.status === 'skipped') {
            continue;
          }
          const error = (result.errors && result.errors[0] && result.errors[0].message) || result.status;
          const shot = (result.attachments || []).find(function (attachment) {
            return attachment.contentType === 'image/png' && attachment.path;
          });
          const values = expectation(error);
          rows.push({
            component: componentOf(spec.title),
            check: path.concat(spec.title).join(' > '),
            expected: values.expected,
            actual: values.actual || error.split('\n')[0].slice(0, 120),
            location: relative(REPO_ROOT, join(RESULTS, '..', spec.file)) + ':' + spec.line,
            screenshot: shot ? relative(REPO_ROOT, shot.path) : ''
          });
        }
      }
    }
    for (const child of suite.suites || []) {
      walk(child, suite.title ? path.concat(suite.title) : path);
    }
  };
  for (const suite of report.suites || []) {
    walk(suite, []);
  }
}

// Node TAP output
const tap = join(RESULTS, 'node.tap');
if (existsSync(tap)) {
  const lines = readFileSync(tap, 'utf8').split('\n');
  let currentFile = '';
  for (let i = 0; i < lines.length; i++) {
    const fileMatch = lines[i].match(/^# Subtest: (.+\.test\.js)$/);
    if (fileMatch) {
      currentFile = fileMatch[1];
    }
    const failMatch = lines[i].match(/^\s*not ok \d+ - (.+)$/);
    if (!failMatch || /\.test\.js$/.test(failMatch[1])) {
      continue;
    }
    const block = lines.slice(i, i + 40).join('\n');
    const values = expectation(block);
    const location = (block.match(/location: '([^']+)'/) || [])[1] || currentFile;
    rows.push({
      component: componentOf(failMatch[1]),
      check: failMatch[1],
      expected: values.expected,
      actual: values.actual || ((block.match(/error: '([^']+)'/) || [])[1] || '').slice(0, 120),
      location: location.replace(REPO_ROOT + '/', ''),
      screenshot: ''
    });
  }
}

const out = ['# Defects', '', 'Generated by `scripts/defects.js` from machine output. ' + rows.length + ' open row(s).', '',
  '| Component | Check | Expected | Actual | Location | Screenshot |', '|---|---|---|---|---|---|'];
for (const row of rows) {
  out.push('| ' + [row.component, row.check, row.expected, row.actual, row.location, row.screenshot].map(function (cell) {
    return String(cell).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  }).join(' | ') + ' |');
}
writeFileSync(OUT, out.join('\n') + '\n');
process.stdout.write('defects: ' + rows.length + ' row(s) -> ' + OUT + '\n');
